### ISSUE TITLE
Linux 6.1.57 / Debian 12 でdebパッケージインストールに失敗する

### ISSUE THREAD

**Issue by eggplants** [tsukumijima/px4_drv#14]
## 概要

[0.5.1](https://github.com/tsukumijima/px4_drv/releases/tag/v0.5.1) のdebパッケージをインストールしようとしたところ、makeビルド時エラーで失敗しました。

DKMSのmakeログをみるに、 `-Werror` が有効になっていることで `implicit-fallthrough` 警告がエラーになっているようです。

これをユーザー側からCFLAGなどで無効化できないか試したのですが効きませんでした。

何か前提を間違えているとか、回避策をご存知でしたら教えていただきたいです。

## 環境

https://gist.github.com/eggplants/56ef75a0b329d8c30e3d03a58502288a#file-setup_mirakc_and_epgs_on_nanopi-sh-L1-L114

- マシン: NanoPi R6S
- OS: FriendlyElec配布イメージ
  - `rk3588-sd-debian-bookworm-core-6.1-arm64-20241022.img.gz`
  - https://drive.google.com/file/d/1eUpJ5DoKkvPDUOsaEt4tBfN7Cg51UCyF/view?usp=drivesdk

```shellsession
$ uname -vorm
6.1.57 #25 SMP Fri Oct 11 19:56:28 CST 2024 aarch64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
```

## エラーログ

```shellsession
$ sudo apt install ./px4-drv-dkms_0.5.1_all.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'px4-drv-dkms' instead of './px4-drv-dkms_0.5.1_all.deb'
The following NEW packages will be installed:
  px4-drv-dkms
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/275 kB of archives.
After this operation, 1,745 kB of additional disk space will be used.
Get:1 /home/eggplants/_tv/px4-drv-dkms_0.5.1_all.deb px4-drv-dkms all 0.5.1 [275 kB]
Selecting previously unselected package px4-drv-dkms.
(Reading database ... 68475 files and directories currently installed.)
Preparing to unpack .../_tv/px4-drv-dkms_0.5.1_all.deb ...
Unpacking px4-drv-dkms (0.5.1) ...
Setting up px4-drv-dkms (0.5.1) ...
Loading new px4_drv-0.5.1 DKMS files...
Building for 6.1.57
Building for architecture aarch64
Building initial module for 6.1.57
Error! Bad return status for module build on kernel: 6.1.57 (aarch64)
Consult /var/lib/dkms/px4_drv/0.5.1/build/make.log for more information.
dpkg: error processing package px4-drv-dkms (--configure):
 installed px4-drv-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 px4-drv-dkms
N: Download is performed unsandboxed as root as file '/home/eggplants/_tv/px4-drv-dkms_0.5.1_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

`/var/lib/dkms/px4_drv/0.5.1/build/make.log`:

```
DKMS make.log for px4_drv-0.5.1 for kernel 6.1.57 (aarch64)
Thu Nov  7 02:11:32 AM JST 2024
'revision.h' was updated.
make[1]: Entering directory '/usr/src/linux-headers-6.1.57'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: aarch64-linux-gcc (ctng-1.25.0-119g-FA) 11.3.0
  You are using:           gcc (Debian 12.2.0-14) 12.2.0
  CC [M]  /var/lib/dkms/px4_drv/0.5.1/build/driver/driver_module.o
  CC [M]  /var/lib/dkms/px4_drv/0.5.1/build/driver/ptx_chrdev.o
  CC [M]  /var/lib/dkms/px4_drv/0.5.1/build/driver/px4_usb.o
In file included from ./include/linux/device.h:15,
                 from /var/lib/dkms/px4_drv/0.5.1/build/driver/px4_usb.c:17:
/var/lib/dkms/px4_drv/0.5.1/build/driver/px4_usb.c: In function ‘px4_usb_probe’:
./include/linux/dev_printk.h:150:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
  150 |         dev_printk_index_wrap(_dev_info, KERN_INFO, dev, dev_fmt(fmt), ##__VA_ARGS__)
      |                               ^
./include/linux/dev_printk.h:110:17: note: in definition of macro ‘dev_printk_index_wrap’
  110 |                 _p_func(dev, fmt, ##__VA_ARGS__);                       \
      |                 ^~~~~~~
/var/lib/dkms/px4_drv/0.5.1/build/driver/px4_usb.c:135:25: note: in expansion of macro ‘dev_info’
  135 |                         dev_info(dev, "Multi-device power control: %s\n",
      |                         ^~~~~~~~
/var/lib/dkms/px4_drv/0.5.1/build/driver/px4_usb.c:138:17: note: here
  138 |                 case USB_PID_PX_W3U4:
      |                 ^~~~
/var/lib/dkms/px4_drv/0.5.1/build/driver/px4_usb.c:154:38: error: this statement may fall through [-Werror=implicit-fallthrough=]
  154 |                         pxmlt5_model = PXMLT5U_MODEL;
      |                         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
/var/lib/dkms/px4_drv/0.5.1/build/driver/px4_usb.c:156:17: note: here
  156 |                 case USB_PID_PX_MLT5PE:
      |                 ^~~~
/var/lib/dkms/px4_drv/0.5.1/build/driver/px4_usb.c:169:38: error: this statement may fall through [-Werror=implicit-fallthrough=]
  169 |                         pxmlt8_model = PXMLT8PE3_MODEL;
      |                         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/var/lib/dkms/px4_drv/0.5.1/build/driver/px4_usb.c:171:17: note: here
  171 |                 case USB_PID_PX_MLT8PE5:
      |                 ^~~~
cc1: all warnings being treated as errors
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/px4_drv/0.5.1/build/driver/px4_usb.o] Error 1
make[1]: *** [Makefile:2057: /var/lib/dkms/px4_drv/0.5.1/build/driver] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.1.57'
make: *** [Makefile:19: px4_drv.ko] Error 2
```

**Comment by tsukumijima** [comment]
ちょうど私も NanoPi-R6S は持っていますが、インストール時期の関係でカーネル 5.10 / Debian 11 のままです。

<img width="607" alt="image" src="https://github.com/user-attachments/assets/de493284-d674-4f4e-9973-d704a08dd9df">

先ほど当該環境で 0.5.1 の Debian パッケージをインストールできるか試してみましたが、正常にコンパイルが完了しインストールすることができました。
したがって、おそらく Debian 11 → 12 での何らかの変化が原因だと推測できます。

> 何か前提を間違えているとか、回避策をご存知でしたら教えていただきたいです。

手元の Linux マシンは現状いずれも比較的古い OS で動かしているため、よく分からないというのが正直なところです。
おそらく新しい gcc バージョンで既定でエラー判定される項目が増えた？のが原因な気はしますが、詳しくはなんとも…。

**Comment by eggplants** [comment]
Raspberry Pi 4でですが、Linux 6.6.31 / RaspberryPi OS Lite (Debian GNU/Linux 12 bookworm) では問題なくインストールできることを確認しているのでLinuxバージョンの方(かOS)が怪しそうです。

環境:
https://gist.github.com/eggplants/bf335687539efd399cd5477f894c9fd2

**Comment by tsukumijima** [comment]
…となると、Debian 12 自体は悪くない可能性が高いかもしれません。
実は friendlyELEC から配布されている公式イメージは『Debian』とは言いつつもかなりカスタムされており、プレーンな Debian とは一部の設定値や構成が異なることを確認しています（具体的にどこまで弄られてるのかはわからないが、GUI 周りが特に顕著）。

たとえば VM で Debian 12 を動かしてみてその中で px4_drv のコンパイルに成功するなら、friendlyELEC のイメージのカスタムが悪いと判断できそうです。
元が ARM 特有の BSP カーネルなので致し方ない面もありますが、もっとプレーンな OS イメージを出してくれないものか…とは思います。

**Comment by eggplants** [comment]
解決しました。

`/usr/src/linux-headers-6.1.57/include/config/auto.conf` を以下のように変更し再度インストールする。

```diff
-CONFIG_CC_IMPLICIT_FALLTHROUGH=-Wimplicit-fallthrough=5
+CONFIG_CC_IMPLICIT_FALLTHROUGH=-Wimplicit-fallthrough=0
```

```shellsession
$ sudo apt install ./px4-drv-dkms_0.5.1_all.deb -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'px4-drv-dkms' instead of './px4-drv-dkms_0.5.1_all.deb'
px4-drv-dkms is already the newest version (0.5.1).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up px4-drv-dkms (0.5.1) ...
Removing old px4_drv-0.5.1 DKMS files...
Deleting module px4_drv-0.5.1 completely from the DKMS tree.
Loading new px4_drv-0.5.1 DKMS files...
Building for 6.1.57
Building for architecture aarch64
Building initial module for 6.1.57
Done.

px4_drv.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/6.1.57/updates/dkms/

Running the post_install script:
'./etc/99-px4video.rules' -> '/etc/udev/rules.d/99-px4video.rules'
'./etc/it930x-firmware.bin' -> '/lib/firmware/it930x-firmware.bin'
depmod...
Scanning processes...
Scanning candidates...
Scanning processor microcode...
Scanning linux images...

Failed to retrieve available kernel versions.

The processor microcode seems to be up-to-date.

Restarting services...
 /etc/needrestart/restart.d/systemd-manager
 systemctl restart avahi-daemon.service containerd.service cron.service lcd2usb.service multipathd.service packagekit.service polkit.service rsyslog.service rtkit-daemon.service ssh.service systemd-journald.service systemd-resolved.service systemd-timesyncd.service systemd-udevd.service upower.service

Service restarts being deferred:
 systemctl restart ModemManager.service
 systemctl restart NetworkManager.service
 systemctl restart bluetooth.service
 /etc/needrestart/restart.d/dbus.service
 systemctl restart docker.service
 systemctl restart getty@tty1.service
 systemctl restart serial-getty@ttyFIQ0.service
 systemctl restart systemd-logind.service
 systemctl restart unattended-upgrades.service
 systemctl restart wpa_supplicant.service

No containers need to be restarted.

User sessions running outdated binaries:
 eggplants @ session #1: apt[15312], bash[1351], newgrp[3608], sshd[1251,1350]
 eggplants @ session #3: sshd[5915,5967]
 eggplants @ user manager service: systemd[1256]

No VM guests are running outdated hypervisor (qemu) binaries on this host.
$ sudo apt show px4-drv-dkms
Package: px4-drv-dkms
Version: 0.5.1
Status: install ok installed
Priority: optional
Section: misc
Maintainer: Dynamic Kernel Modules Support Team <pkg-dkms-maint@lists.alioth.debian.org>
Installed-Size: 1745 kB
Provides: px4-drv-modules (= 0.5.1)
Depends: dkms (>= 1.95)
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: px4-drv driver in DKMS format.
```

**Comment by tsukumijima** [comment]
BSP カーネルヘッダーでの設定値の差が原因でしたか…。ともかく解決したようでよかったです。

**Comment by eggplants** [comment]
…しかし `sudo modprobe px4_drv` するとエラーになります。

```shellsession
$ sudo modprobe px4_drv
modprobe: ERROR: could not insert 'px4_drv': Exec format error
$ sudo modprobe px4_drv -v
insmod /lib/modules/6.1.57/updates/dkms/px4_drv.ko
modprobe: ERROR: could not insert 'px4_drv': Exec format error
```

こちらは別問題かつカーネルバージョンの差異による既知の問題のようなので、自分の方で対処しようと思います。(最悪 [Debian 11 bullseye / Linux 5.10の古いOSイメージ](https://drive.google.com/file/d/1wfr-ZcSpmTKwAF5XmYM1y64-YrIRrn-m/view?usp=drive_link)を試してみます。)
ご対応ありがとうございました。

**Comment by eggplants** [comment]
NanoPi R6S / [rk3568-sd-debian-bookworm-core-6.1-arm64-20250811.img](https://drive.google.com/file/d/1hA3pUcZzdfSN1htq-3Nxn5ECr0EA1sa6/view?usp=drive_link) / px4_drv v0.5.5 を試してみたところ、正常に `sudo modprobe px4_drv` まで成功しました。

詳細: https://gist.github.com/eggplants/afaa31d65a1603f4868c0c400d7d5430

```shellsession
$ uname -vorm
6.1.118 #26 SMP Thu Aug  7 14:45:40 CST 2025 aarch64 GNU/Linux
$ lsmod | grep  px4_drv
px4_drv               163840  0
```
